export const mockUser = {
   id: "mock-user",
   email: "mock@runningman.com",
   name: "Mocky Runner",
   age: 28,
   height: 175.5,
   gender: "male",
   weight: 68.2,
   theme: "speed",
   location: "Bangkok, Thailand",
   conditionPriority: {
      cloudiness: 1,
      "sunset-time": 1,
      "sunrise-time": 1,

      "feels-like": 2,
      "heat-index": 2,
      visibility: 2,
      "wind-speed": 2,
      pollen: 2,

      temperature: 3,
      humidity: 3,
      "uv-index": 3,
      "rain-chance": 3,
      aqi: 3,
      "pm2.5": 3,
   },
   notificationEnabled: true,
};
