export const mockRoutes = [
   {
      title: "Morning Park Run",
      distance: 5.2,
      laps: 2,
      location: "Lumphini Park",
      note: "Flat loop, lots of shade",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Evening Riverside",
      distance: 8.0,
      laps: 1,
      location: "Chao Phraya Riverside",
      note: "Windy and scenic",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Stadium Intervals",
      distance: 3.0,
      laps: 6,
      location: "Rajamangala Stadium",
      note: "Good for speedwork",
      userId: "mock-user",
      runType: "interval",
   },
   {
      title: "Hill Challenge",
      distance: 7.5,
      laps: 1,
      location: "Benjakitti Forest",
      note: "Hilly section near exit gate",
      userId: "mock-user",
      runType: "hill-training",
   },
   {
      title: "Sunset Jog",
      distance: 4.0,
      laps: 2,
      location: "Chatuchak Park",
      note: "Nice view during sunset",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Night City Loop",
      distance: 6.3,
      laps: 1,
      location: "Sathorn - Silom Loop",
      note: "Bright and active area",
      userId: "mock-user",
      runType: "daily-miles",
   },
   {
      title: "Bridge Repeats",
      distance: 2.0,
      laps: 5,
      location: "Rama VIII Bridge",
      note: "Great for hill strength",
      userId: "mock-user",
      runType: "hill-training",
   },
   {
      title: "Park Recovery",
      distance: 3.5,
      laps: 2,
      location: "Queen Sirikit Park",
      note: "Post-long-run recovery route",
      userId: "mock-user",
      runType: "recovery",
   },
   {
      title: "Bang Krachao Long Run",
      distance: 12.0,
      laps: 1,
      location: "Bang Krachao",
      note: "Quiet, perfect for long runs",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "Morning Tempo",
      distance: 6.0,
      laps: 1,
      location: "Suan Luang Rama IX",
      note: "Wide lanes, less crowded",
      userId: "mock-user",
      runType: "tempo",
   },
   {
      title: "Morning Park Run",
      distance: 5.2,
      laps: 2,
      location: "Lumphini Park",
      note: "Flat loop, lots of shade",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Evening Riverside",
      distance: 8.0,
      laps: 1,
      location: "Chao Phraya Riverside",
      note: "Windy and scenic",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Stadium Intervals",
      distance: 3.0,
      laps: 6,
      location: "Rajamangala Stadium",
      note: "Good for speedwork",
      userId: "mock-user",
      runType: "interval",
   },
   {
      title: "Hill Challenge",
      distance: 7.5,
      laps: 1,
      location: "Benjakitti Forest",
      note: "Hilly section near exit gate",
      userId: "mock-user",
      runType: "hill-training",
   },
   {
      title: "Sunset Jog",
      distance: 4.0,
      laps: 2,
      location: "Chatuchak Park",
      note: "Nice view during sunset",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Night City Loop",
      distance: 6.3,
      laps: 1,
      location: "Sathorn - Silom Loop",
      note: "Bright and active area",
      userId: "mock-user",
      runType: "daily-miles",
   },
   {
      title: "Bridge Repeats",
      distance: 2.0,
      laps: 5,
      location: "Rama VIII Bridge",
      note: "Great for hill strength",
      userId: "mock-user",
      runType: "hill-training",
   },
   {
      title: "Park Recovery",
      distance: 3.5,
      laps: 2,
      location: "Queen Sirikit Park",
      note: "Post-long-run recovery route",
      userId: "mock-user",
      runType: "recovery",
   },
   {
      title: "Bang Krachao Long Run",
      distance: 12.0,
      laps: 1,
      location: "Bang Krachao",
      note: "Quiet, perfect for long runs",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "Morning Tempo",
      distance: 6.0,
      laps: 1,
      location: "Suan Luang Rama IX",
      note: "Wide lanes, less crowded",
      userId: "mock-user",
      runType: "tempo",
   },
   {
      title: "Canal Side Easy",
      distance: 5.0,
      laps: 1,
      location: "Khlong Saen Saep Path",
      note: "Can get hot mid-day",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Airport Run",
      distance: 10.0,
      laps: 1,
      location: "Suvarnabhumi Observation Deck",
      note: "Very quiet in the morning",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "College Campus",
      distance: 2.5,
      laps: 3,
      location: "Chulalongkorn University",
      note: "Great early morning route",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Highway Overpass",
      distance: 3.2,
      laps: 4,
      location: "Kaset-Nawamin Road",
      note: "Challenging elevation",
      userId: "mock-user",
      runType: "hill-training",
   },
   {
      title: "Railway Side Path",
      distance: 6.5,
      laps: 1,
      location: "BTS Sukhumvit Line Side",
      note: "Loud but flat",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Neighborhood Loops",
      distance: 2.0,
      laps: 5,
      location: "Ekkamai Residential",
      note: "Safe but repetitive",
      userId: "mock-user",
      runType: "daily-miles",
   },
   {
      title: "Marathon Simulation",
      distance: 18.0,
      laps: 1,
      location: "Rama 9 Outer Ring",
      note: "Use with hydration setup",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "Forest Trail",
      distance: 7.0,
      laps: 1,
      location: "Nong Bon Lake",
      note: "Some gravel sections",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "Waterfront Run",
      distance: 6.8,
      laps: 1,
      location: "Asiatique to IconSiam",
      note: "Tourist-heavy after 9am",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Industrial Zone",
      distance: 4.5,
      laps: 2,
      location: "Lat Krabang Industrial",
      note: "Early morning only",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Farm Fields",
      distance: 5.5,
      laps: 1,
      location: "Pathum Thani Rice Fields",
      note: "Muddy if it rained",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Weekend Long Run",
      distance: 15.0,
      laps: 1,
      location: "Srinakarin Trail",
      note: "Long and quiet",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "Run Commute",
      distance: 3.8,
      laps: 1,
      location: "From Condo to Office",
      note: "Busy intersections",
      userId: "mock-user",
      runType: "daily-miles",
   },
   {
      title: "Late Night Sprints",
      distance: 2.4,
      laps: 3,
      location: "Bangkok University Track",
      note: "Floodlights available",
      userId: "mock-user",
      runType: "speed-work",
   },
   {
      title: "Suburb Tempo",
      distance: 5.7,
      laps: 1,
      location: "Bang Na Residential Area",
      note: "Cars after 7am",
      userId: "mock-user",
      runType: "tempo",
   },
   {
      title: "Rainy Day Route",
      distance: 3.0,
      laps: 2,
      location: "Under Rama IX Expressway",
      note: "Covered, good for wet days",
      userId: "mock-user",
      runType: "recovery",
   },
   {
      title: "Fitness Park Cruise",
      distance: 4.2,
      laps: 2,
      location: "Thai-Japanese Stadium",
      note: "Smooth track, quiet evenings",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Reservoir Perimeter",
      distance: 9.0,
      laps: 1,
      location: "Prapradaeng Reservoir",
      note: "Flat but sun-exposed",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "Museum Grounds Jog",
      distance: 3.6,
      laps: 2,
      location: "Bangkok National Museum",
      note: "Not crowded, peaceful",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Seaside Breeze",
      distance: 7.8,
      laps: 1,
      location: "Bangsaen Beach",
      note: "Great for weekend trips",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "Temple Loop",
      distance: 2.8,
      laps: 3,
      location: "Wat Arun Perimeter",
      note: "Spiritual and scenic",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "City Garden Trail",
      distance: 5.4,
      laps: 1,
      location: "Benjasiri Park",
      note: "Shady, moderate crowd",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Airport Rail Link Path",
      distance: 11.0,
      laps: 1,
      location: "Phaya Thai to Suvarnabhumi",
      note: "Urban and gritty",
      userId: "mock-user",
      runType: "long-run",
   },
   {
      title: "Dawn Patrol",
      distance: 6.1,
      laps: 1,
      location: "Victory Monument Loop",
      note: "Best before 6am",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "University Oval",
      distance: 1.2,
      laps: 8,
      location: "Thammasat University",
      note: "Safe campus, well-lit",
      userId: "mock-user",
      runType: "interval",
   },
   {
      title: "Swamp Edge Path",
      distance: 4.9,
      laps: 1,
      location: "Bang Khen Swamp",
      note: "Mosquito repellent needed",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Business District Dash",
      distance: 5.0,
      laps: 1,
      location: "Silom to Wireless Road",
      note: "Early hours only",
      userId: "mock-user",
      runType: "daily-miles",
   },
   {
      title: "Zoo to Mall Route",
      distance: 3.3,
      laps: 1,
      location: "Dusit Zoo to Siam Paragon",
      note: "Mixed terrain",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Pedestrian Skywalk Run",
      distance: 2.5,
      laps: 2,
      location: "BTS Skywalk (Siam – Chidlom)",
      note: "Avoid rush hours",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Red Line Test Loop",
      distance: 6.6,
      laps: 1,
      location: "Bang Sue to Lak Si",
      note: "Great at dawn",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Old Town Ramble",
      distance: 5.5,
      laps: 1,
      location: "Rattanakosin Island",
      note: "Watch for tourists",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Water Plant Perimeter",
      distance: 3.9,
      laps: 2,
      location: "Min Buri Water Facility",
      note: "Peaceful and secure",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Warehouse Track",
      distance: 4.4,
      laps: 2,
      location: "Bang Sue Logistics Yard",
      note: "Surprisingly quiet",
      userId: "mock-user",
      runType: "easy",
   },
   {
      title: "Metro Line Sprint",
      distance: 5.6,
      laps: 1,
      location: "Purple Line Parkway",
      note: "Shade depends on time",
      userId: "mock-user",
      runType: "progression",
   },
   {
      title: "Midnight Market Loop",
      distance: 2.2,
      laps: 3,
      location: "Huai Khwang Market",
      note: "Fun at night, watch for vendors",
      userId: "mock-user",
      runType: "daily-miles",
   },
];
