export const mockUser = {
   id: "mock-user",
   email: "mock@runningman.com",
   name: "Mocky Runner",
   age: 28,
   height: 175.5,
   gender: "male",
   weight: 68.2,
   theme: "speed",
   location: "Bangkok, Thailand",
   conditionPreference: {
      temperature: 2,
      "feels-like": 1,
      "heat-index": 1,
      humidity: 2,
      cloudiness: 0,
      "uv-index": 2,
      visibility: 1,
      "wind-speed": 1,
      "rain-chance": 2,
      "sunset-time": 0,
      "sunrise-time": 0,
      aqi: 2,
      "pm2.5": 2,
      pollen: 1,
   },
   notificationEnabled: true,
};
