export const conditionPreference = {
   cloudiness: 1,
   "sunset-time": 1,
   "sunrise-time": 1,
   "feels-like": 2,
   "heat-index": 2,
   visibility: 2,
   "wind-speed": 2,
   pollen: 2,
   temperature: 3,
   humidity: 3,
   "uv-index": 3,
   "rain-chance": 3,
   aqi: 3,
   "pm2.5": 3,
};
