export const conditionPreference = {
   cloudiness: 1,
   "sunset-time": 1,
   "sunrise-time": 1,
   "feels-like": 3,
   "heat-index": 2,
   visibility: 2,
   "wind-speed": 2,
   pollen: 2,
   temperature: 3,
   humidity: 2,
   "uv-index": 2,
   "rain-chance": 2,
   aqi: 2,
   "pm2.5": 2,
};
