export function getDemoRuns(userId: string) {
   return [
      {
         userId,
         title: "Heartbreak Healing Run",
         distance: 5.2,
         duration: 32,
         laps: 2,
         location: "Lumphini Park",
         runType: "easy",
         mood: "low-energy",
         gear: "Nike Pegasus 41",
         note: "Legs felt heavy, heart heavier.",
         dateTime: "2025-07-08T06:30:00Z",
      },
      {
         userId,
         title: "Birthday PR Smash",
         distance: 10.0,
         duration: 50,
         laps: 3,
         location: "Chatuchak Park",
         runType: "tempo",
         mood: "electrifying",
         gear: "Adidas Boston 12",
         note: "New age, new pace!",
         dateTime: "2025-07-04T07:00:00Z",
      },
      {
         userId,
         title: "Sunday Soul Cleanser",
         distance: 7.5,
         duration: 42,
         laps: 2,
         location: "Benjakitti Park",
         runType: "recovery",
         mood: "standard",
         gear: "Asics Novablast 5",
         note: "Peaceful. Legs okay.",
         dateTime: "2025-07-06T17:30:00Z",
      },
      {
         userId,
         title: "Run from Depression",
         distance: 5.0,
         duration: 30,
         laps: 1,
         location: "Queen Sirikit Park",
         runType: "daily-miles",
         mood: "flowing",
         gear: "Hoka Clifton 9",
         note: "Running helps.",
         dateTime: "2025-07-02T18:00:00Z",
      },
      {
         userId,
         title: "Post-Meeting Rage Jog",
         distance: 6.0,
         duration: 36,
         laps: 2,
         location: "Lumphini Park",
         runType: "progression",
         mood: "electrifying",
         gear: "Nike Invincible 3",
         note: "Faster with every thought.",
         dateTime: "2025-07-09T19:15:00Z",
      },
      {
         userId,
         title: "Oops All Hills",
         distance: 8.0,
         duration: 48,
         laps: 3,
         location: "Rama IX Park",
         runType: "hill-training",
         mood: "low-energy",
         gear: "Asics Gel-Kayano 30",
         note: "Regret at km 3.",
         dateTime: "2025-07-01T06:45:00Z",
      },
      {
         userId,
         title: "Sunset Chaser",
         distance: 5.5,
         duration: 33,
         laps: 1,
         location: "Benjasiri Park",
         runType: "easy",
         mood: "flowing",
         gear: "New Balance Rebel V4",
         note: "Colors were insane.",
         dateTime: "2025-07-03T18:40:00Z",
      },
      {
         userId,
         title: "Speed Demon",
         distance: 5.2,
         duration: 25,
         laps: 4,
         location: "Chatuchak Park",
         runType: "interval",
         mood: "transcendent",
         gear: "Adidas Takumi Sen 10",
         note: "Felt like flying.",
         dateTime: "2025-07-05T07:10:00Z",
      },
      {
         userId,
         title: "Monsoon Madness",
         distance: 6.3,
         duration: 38,
         laps: 2,
         location: "Lumphini Park",
         runType: "fartlek",
         mood: "standard",
         gear: "Nike Pegasus Trail 4",
         note: "Slipped once. Worth it.",
         dateTime: "2025-07-07T17:00:00Z",
      },
      {
         userId,
         title: "Midnight Clarity",
         distance: 5.1,
         duration: 31,
         laps: 1,
         location: "Benjakitti Park",
         runType: "easy",
         mood: "flowing",
         gear: "Asics Novablast 5",
         note: "City lights. Clear mind.",
         dateTime: "2025-07-10T00:15:00Z",
      },
      {
         userId,
         title: "Leg Day Skip Excuse",
         distance: 9.1,
         duration: 60,
         laps: 3,
         location: "Lumphini Park",
         runType: "long-run",
         mood: "low-energy",
         gear: "Hoka Clifton 9",
         note: "Legs dead. Still counts.",
         dateTime: "2025-07-11T06:00:00Z",
      },
      {
         userId,
         title: "Run Club Shenanigans",
         distance: 6.0,
         duration: 34,
         laps: 2,
         location: "Benjasiri Park",
         runType: "tempo",
         mood: "electrifying",
         gear: "Nike Zoom Fly 5",
         note: "Fast crew today.",
         dateTime: "2025-07-05T18:00:00Z",
      },
      {
         userId,
         title: "Zoned Out Zen Jog",
         distance: 5.0,
         duration: 31,
         laps: 1,
         location: "Queen Sirikit Park",
         runType: "recovery",
         mood: "standard",
         gear: "Asics Novablast 5",
         note: "Didn’t think, just ran.",
         dateTime: "2025-07-07T06:50:00Z",
      },
      {
         userId,
         title: "Wake Up Legs",
         distance: 5.3,
         duration: 29,
         laps: 1,
         location: "Benjakitti Park",
         runType: "easy",
         mood: "standard",
         gear: "New Balance Rebel V4",
         note: "Warm-up before gym.",
         dateTime: "2025-07-02T06:10:00Z",
      },
      {
         userId,
         title: "Pre-Date Nerves Buster",
         distance: 5.4,
         duration: 28,
         laps: 1,
         location: "Chatuchak Park",
         runType: "easy",
         mood: "flowing",
         gear: "Adidas Boston 12",
         note: "Faster than I expected.",
         dateTime: "2025-07-08T16:45:00Z",
      },
      {
         userId,
         title: "Race Simulation Day",
         distance: 10.0,
         duration: 46,
         laps: 3,
         location: "Rama IX Park",
         runType: "race",
         mood: "electrifying",
         gear: "Nike Vaporfly 3",
         note: "Mental game strong.",
         dateTime: "2025-07-06T06:00:00Z",
      },
      {
         userId,
         title: "Angry Tempo Rage",
         distance: 7.2,
         duration: 39,
         laps: 2,
         location: "Lumphini Park",
         runType: "tempo",
         mood: "electrifying",
         gear: "Asics Magic Speed 3",
         note: "Cleared my head.",
         dateTime: "2025-07-03T19:00:00Z",
      },
      {
         userId,
         title: "Trash Run, Great Coffee",
         distance: 5.1,
         duration: 34,
         laps: 2,
         location: "Benjakitti Park",
         runType: "daily-miles",
         mood: "low-energy",
         gear: "Nike Structure 25",
         note: "Run bad, vibes post-run amazing.",
         dateTime: "2025-07-04T07:30:00Z",
      },
      {
         userId,
         title: "Strides + Chill",
         distance: 5.0,
         duration: 27,
         laps: 1,
         location: "Queen Sirikit Park",
         runType: "speed-work",
         mood: "flowing",
         gear: "Adidas Takumi Sen 10",
         note: "Short bursts, good form.",
         dateTime: "2025-07-10T18:10:00Z",
      },
      {
         userId,
         title: "Almost Skipped Run",
         distance: 5.3,
         duration: 31,
         laps: 1,
         location: "Benjakitti Park",
         runType: "easy",
         mood: "standard",
         gear: "Asics Novablast 5",
         note: "Glad I didn’t skip.",
         dateTime: "2025-07-11T07:20:00Z",
      },
   ];
}
