export function getDemoRoutes(userId: string) {
   return [
      {
         userId,
         title: "Easy Recovery Loop",
         distance: 5.0,
         duration: null,
         laps: 1,
         location: "Lumphini Park",
         runType: "easy",
         note: `A gentle paced route focusing on active recovery. Suitable after intense training days. Mostly flat terrain with shaded paths. Keep heart rate low, breathing steady.`,
      },
      {
         userId,
         title: "Medium Intensity Interval",
         distance: null,
         duration: 40,
         laps: 2,
         location: "Chatuchak Park",
         runType: "interval",
         note: `Alternating between moderate hard efforts and easy jogs. Warm-up for 10 minutes, then 5 x 3 minutes at 80-90% effort with 2 min jog recoveries. Cool down at the end.`,
      },
      {
         userId,
         title: "Long Slow Distance Run",
         distance: 12.0,
         duration: null,
         laps: 3,
         location: "Rama IX Park",
         runType: "long-run",
         note: `Designed for endurance building with slow, steady pacing. Focus on consistent effort and breathing control. Route covers scenic lake views and gentle hills.`,
      },
      {
         userId,
         title: "Tempo Challenge Route",
         distance: null,
         duration: 45,
         laps: 2,
         location: "Benjakitti Park",
         runType: "tempo",
         note: `Sustain a comfortably hard pace slightly below race effort for the bulk of the run. Begin with a 10-minute easy jog, then 25 minutes tempo, and finish with a cool-down.`,
      },
      {
         userId,
         title: "Hill Sprint Circuit",
         distance: 5.2,
         duration: null,
         laps: 4,
         location: "Rama IX Park",
         runType: "hill-training",
         note: `Short uphill sprints followed by walking recoveries. Target explosive power and leg strength. Warm up thoroughly, then 8 x 30 seconds hill sprints with full recovery.`,
      },
      {
         userId,
         title: "Fartlek Fun Route",
         distance: null,
         duration: 40,
         laps: 1,
         location: "Benjasiri Park",
         runType: "fartlek",
         note: `Unstructured speed play with bursts of faster running mixed into an easy jog. Perfect for improving speed and mental freshness. Feel free to vary intensity based on how you feel.`,
      },
      {
         userId,
         title: "Progression Run",
         distance: 6.0,
         duration: null,
         laps: 2,
         location: "Queen Sirikit Park",
         runType: "progression",
         note: `Start slow, gradually increase pace every 10 minutes, finishing near race pace. Helps teach controlled pacing and finishing strength.`,
      },
      {
         userId,
         title: "Speed Work Session",
         distance: null,
         duration: 25,
         laps: 3,
         location: "Chatuchak Park",
         runType: "speed-work",
         note: `Focus on short, fast repeats with full recoveries. 10 minutes warm-up, 6 x 400m at 95% effort, 2-minute rest between reps, followed by a cool-down.`,
      },
      {
         userId,
         title: "Recovery Jog",
         distance: 5.0,
         duration: null,
         laps: 1,
         location: "Benjakitti Park",
         runType: "recovery",
         note: `Easy pace jog to flush out lactic acid and speed recovery after hard workouts. Keep effort low, relaxed breathing, and enjoy the scenery.`,
      },
      {
         userId,
         title: "Race Pace Simulation",
         distance: null,
         duration: 48,
         laps: 3,
         location: "Lumphini Park",
         runType: "race",
         note: `Practice maintaining goal race pace for sustained periods. Includes warm-up, 3 x 3 km at race pace with short jog recoveries, and a cool-down phase.`,
      },
   ];
}
